name: macOS

on: [push]

jobs:
  build:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
      # TODO: Remove this step once Xcode 12+/Swift 5.3 is default
    - name: Pick the right Xcode version
      run: sudo xcode-select -s /Applications/Xcode_12.app
    - name: Build
      run: swift build
    - name: Test
      run: swift test
